spring.application.name=Film
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Film_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.mvc.problemdetails.enabled=true
